/**
 * Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
// 
// IMyCapability.java
// Wed May 21 15:24:25 CEST 2008
// Generated by the Apache Muse Code Generation Tool
// 
package org.n52.ses.api.ws;

import java.util.Date;

import javax.xml.namespace.QName;

import org.apache.muse.core.Resource;
import org.apache.muse.ws.addressing.EndpointReference;
import org.w3c.dom.Element;

/**
 * Interface for the register publisher method.
 *
 */
public interface IRegisterPublisher {
	
	/**
	 * standard prefix for XML QNames
	 */
    String PREFIX = "tns";

    /**
     * namespace for the register publisher operation name
     */
    String NAMESPACE_URI = "http://docs.oasis-open.org/wsn/b-2";

    /**
     * registers a publisher
     * 
     * @param PublisherReference endpoint reference of the publisher
     * @param Topic topic on which the publisher publishes
     * @param Demand <code>true</code>if the publisher is in "on demand" mode
     * @param InitialTerminationTime termination time for the publisher
     * @param domElem registration parameters in XML
     * @return XML response
     * @throws Exception if an error occurred on destroying
     */
    public Resource registerPublisher(EndpointReference PublisherReference, QName[] Topic, boolean Demand, Date InitialTerminationTime, org.w3c.dom.Element domElem) throws Exception;

	public void reRegisterPublisher(EndpointReference publisherReference,
			QName[] topic, boolean demand, Date initialTerminationTime,
			Element sensorML, IPublisherEndpoint publisherCapability);

}